USE master
GO
--FINALLY, SHOULD JOIN DATABASES TO SECONDARY AG FROM SECONDARY REPLICA IN SECONDARY SIDE
ALTER DATABASE [Appdashboard] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [Corealert] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [CoreAuth] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [Corecardconnect] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [CoreIssue] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [CoreLibrary] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [CoreMoney] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [Dashboard] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
ALTER DATABASE [KMMDB] SET HADR AVAILABILITY GROUP = [PPGPDAPPAG]
